# Generated by Django 5.0.1 on 2024-01-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api42", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(default="in progress", max_length=255),
        ),
    ]
