# Generated by Django 5.0.1 on 2024-01-21 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api42", "0003_alter_game_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="due_data",
            new_name="due_date",
        ),
    ]
