version: '3.8'

services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    image: "s_postgres"
    container_name: db
    networks:
      - back_v
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - back_v
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_INTERNAL_PORT}"
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

networks:
  back_v:

volumes:
  pg_data:
  pgadmin_data:

 
